### ISSUE TITLE
Imágenes para Quienes Somos

### ISSUE THREAD

**Issue by RoberOusset** [JuanAgusAlej/DrinkHub#6]
Favor de pasarme las fotos de cada uno. Gracias!

**Comment by JuanAgusAlej** [comment]
![WhatsApp Image 2021-05-03 at 20 58 40](https://user-images.githubusercontent.com/93957096/149343767-6b3028ea-e322-42a7-a35a-478ac6d2a840.jpeg)

**Comment by RoberOusset** [comment]
Recibi todo por whatsapp. GRACIAS!
